name: Firebase Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
        env:
          CI: false
      - name: Install Dependencies
        run: npm install
      - name: Build
        env:
          CI: false
        run: npm run build
      - name: Deploy to Firebase
        env:
          CI: false
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting
 